LOCAL_SCRIPTS="$HOME/.local/bin/scripts/"
SHELL_SESSIONS_DISABLE=1    # https://apple.stackexchange.com/a/427568

export EDITOR="code --wait"
export LANG=en_US.UTF-8     # Unicode sorting instead ASCII-based (e.g. in `ls`, `sort`)

[[ -f ~/.config/work/env ]] && source ~/.config/work/env || :
