LOCAL_BIN="$HOME/.local/bin/"
LOCAL_SCRIPTS="${LOCAL_BIN}scripts/"
SHELL_SESSIONS_DISABLE=1    # https://apple.stackexchange.com/a/427568

export EDITOR="code --wait"
export LANG=en_US.UTF-8     # Unicode sorting instead ASCII-based (e.g. in `ls`, `sort`)

[[ -f ~/.config/work/dotfiles/zshenv ]] && source ~/.config/work/dotfiles/zshenv || :
