#!/usr/bin/env bash

# Auto load from completions dir
MY_COMPLETIONS_DIR=~/.bash_completion.d
for i in $MY_COMPLETIONS_DIR/*; do
    [[ ( -f $i || -h $i ) && -r $i ]] && . "$i"
done

# Load dynamically generated completions
eval "`pip completion --bash`"

# Bash complete the git alias 'g'
complete -o bashdefault -o default -o nospace -F _git g 2>/dev/null \
    || complete -o default -o nospace -F _git g
