tap "alexanderwillner/tap"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "teaxyz/pkgs"

# Core installs

brew "alexanderwillner/tap/things.sh"
brew "asciinema"
brew "autojump"
brew "awscli"
brew "exiftool"
brew "fx"                     # tool for json
brew "git"
brew "httpie"
brew "hugo"
brew "jq"                     # tool for json
brew "mas"                    # tool for App Store
brew "md5sha1sum"
brew "testdisk"
brew "tldr"
brew "trash"
brew "tree"
brew "watch"
brew "wget"
brew "teaxyz/pkgs/tea-cli"    # package manager for multi-lang versions

cask "1password"
cask "choosy"
cask "disk-inventory-x"
cask "gitx"
cask "google-cloud-sdk"
cask "google-chrome"
cask "keepingyouawake"
cask "maccy"
cask "menumeters"
cask "netnewswire"
cask "orbstack"               # replacement for "docker"
cask "qlmarkdown"             # extension for Quick Look
cask "rectangle"
cask "slack"
cask "syncthing"
cask "syntax-highlight"       # extension for Quick Look
cask "textmate"               # TODO: replace with "visual-studio-code" + all commands `mate` ➔ `code` + core `vscode` extensions
cask "typora"

mas "1Password for Safari", id: 1569813296
mas "Streaks", id: 963034692
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835

# Temp installs

brew "bash-completion"        # TODO: drop for default zsh shell
brew "pdftohtml"
brew "thefuck"
brew "vcprompt"               # TODO: drop for default zsh prompt

cask "aerial"
cask "around"
cask "discord"
cask "firefox"
cask "keycastr"
cask "libreoffice"
cask "oversight"
cask "piezo"
cask "postman"
cask "tunnelbear"
cask "vlc"

mas "Randomness", id: 673815312
mas "Sim Daltonism", id: 693112260
mas "Exporter", id: 1099120373                    # tool for Apple Notes => Markdown conversion
mas "GarageBand", id: 682658836
mas "Hush", id: 1544743900                        # safari extension for cookies consent
mas "Just Focus", id: 1142151959                  # tool for pomodoro intervals
mas "Super Agent", id: 1568262835                 # safari extension for cookies consent
