tap "alexanderwillner/tap"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "teaxyz/pkgs"

# Core installs

brew "alexanderwillner/tap/things.sh"
brew "asciinema"
brew "autojump"
brew "awscli"
brew "exiftool"
brew "fx"                     # tool for json
brew "git"
brew "httpie"
brew "hugo"
brew "jq"                     # tool for json
brew "mas"                    # tool for App Store
brew "md5sha1sum"
brew "testdisk"
brew "tldr"
brew "trash"
brew "tree"
brew "watch"
brew "wget"
brew "teaxyz/pkgs/tea-cli"

cask "1password"
cask "choosy"
cask "disk-inventory-x"
cask "google-cloud-sdk"
cask "google-chrome"
cask "keepingyouawake"
cask "maccy"
cask "menumeters"
cask "netnewswire"
cask "orbstack"               # replacement for "docker"
cask "qlmarkdown"             # extension for Quick Look
cask "rectangle"
cask "slack"
cask "syncthing"
cask "syntax-highlight"       # extension for Quick Look
cask "textmate"
cask "typora"

mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835

# Temp installs

brew "bash-completion"        # TODO: drop for default zsh shell
brew "pdftohtml"
brew "thefuck"
brew "vcprompt"               # TODO: drop for default zsh prompt

cask "aerial"
cask "around"
cask "discord"
cask "firefox"
cask "keycastr"
cask "libreoffice"
cask "oversight"
cask "piezo"
cask "postman"
cask "tunnelbear"
cask "vlc"

mas "Randomness", id: 673815312
