# ALIASES & FUNCTIONS
[[ -r ~/.bash_aliases ]] && source ~/.bash_aliases

# PATHS
LOCAL_CODE=~/Documents/C/Code/Shell
LOCAL_SCRIPTS=$LOCAL_CODE/scripts.git
PATH=`brew --prefix ruby`/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=/usr/local/bin:$PATH
PATH=$PATH:/Applications/Xcode.app/Contents//Developer/Tools
PATH=$PATH:$LOCAL_SCRIPTS
export PATH

# ENVIRONMENT CONFIG
shopt -s cdspell
export EDITOR='mate -w'
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

[[ -r ~/.colors.sh ]] && source ~/.colors.sh
# HF: FIXME: show a message if doesn't exits; load the PS's otherwise
# e.g. PS1='[missing ~/.color.sh] \h:\W \u\$ '
if isadmin $USER; then
    export PS1="\n${RED}\h: ${BOLD_RED}\w\n${RED}\u\$${RESET} [\A] ${RESET}"
else
    export PS1="\n${WHITE}\h: ${CYAN}\w\n${WHITE}\u\$${RESET} [\A]${YELLOW}\${VIRTUAL_ENV:+ (\${VIRTUAL_ENV##*/})} ${YELLOW}\$(vcprompt -f '[%n:%b]%m%u ')${RESET}"
fi
    # (deprecated: irrelevant since using "vcprompt")
    # GIT_PS1_SHOWDIRTYSTATE=           # unstaged (*) and staged (+) changes
    # GIT_PS1_SHOWSTASHSTATE=1          # something stashed ($) 
    # GIT_PS1_SHOWUNTRACKEDFILES=       # untracked files (%)
    # export PS1='\h:\w \u`__git_ps1`\$ '

# BASH ETERNAL HISTORY
shopt -s histappend
export HISTCONTROL=ignoredups:erasedups:ignorespace
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="%F %T "

# GO ENVIRONMENT
export GOPATH=$HOME/Documents/C/Code/Go

# JAVA ENVIRONMENT
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"

# PYTHON VIRTUAL ENVS
# HF: FIXME: Set only if virtualenv stuff is installed
# export VIRTUAL_ENV_DISABLE_PROMPT=1
# export PIP_VIRTUALENV_BASE=$WORKON_HOME
# export PIP_RESPECT_VIRTUALENV=true
# source virtualenvwrapper.sh

# BASH COMPLETION
[[ -f `brew --prefix`/etc/bash_completion ]] && source `brew --prefix`/etc/bash_completion

# 3rd PARTY SOURCES
[[ -f `brew --prefix`/etc/autojump.sh ]] && source `brew --prefix`/etc/autojump.sh
[[ -f `brew --prefix`/share/chtf/chtf.sh ]] && source `brew --prefix`/share/chtf/chtf.sh
[[ -f $LOCAL_SCRIPTS/mvncolor.sh ]] && source $LOCAL_SCRIPTS/mvncolor.sh

# Work related
[[ -f $LOCAL_CODE/dotfiles_work.git/equalexperts/bash_profile.sh ]] && source $LOCAL_CODE/dotfiles_work.git/equalexperts/bash_profile.sh
[[ -f $LOCAL_CODE/dotfiles_work.git/uxforms/bash_profile.sh ]] && source $LOCAL_CODE/dotfiles_work.git/uxforms/bash_profile.sh
