# ALIASES & FUNCTIONS
[[ -r ~/.bash_aliases ]] && source ~/.bash_aliases

# GO ENVIRONMENT
export GOPATH=~/Documents/C/Code/Go

# PATHS
LOCAL_SCRIPTS=~/Documents/C/Code/Shell/scripts.git

PATH=/usr/local/sbin/:$PATH
PATH=$PATH:/Applications/Xcode.app/Contents/Developer/Tools
PATH=$PATH:$LOCAL_SCRIPTS
PATH=$PATH:$GOPATH
export PATH

# ENVIRONMENT CONFIG
shopt -s cdspell
export EDITOR='mate -w'
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

source_from_path ~/.colors.sh
# HF: FIXME: show a message if doesn't exits; load the PS's otherwise
# e.g. PS1='[missing ~/.color.sh] \h:\W \u\$ '
if [[ "$USER" == "admin" ]]; then
    export PS1="\n${RED}\h: ${BOLD_RED}\w\n${RED}\u\$${RESET} [\A] ${RESET}"
else
    PS_FULL="\n${WHITE}\h: ${CYAN}\w\n${WHITE}\u\$${RESET} [\A]${YELLOW}\${VIRTUAL_ENV:+ (\${VIRTUAL_ENV##*/})} ${YELLOW}\$(vcprompt -f '[%n:%b]%m%u ')${RESET}"
    PS_DEMO="\n${WHITE}\h: ${CYAN}\W\n${WHITE}\u\$${RESET}${YELLOW}\${VIRTUAL_ENV:+ (\${VIRTUAL_ENV##*/})} ${YELLOW}\$(vcprompt -f '[%n:%b]%m%u ')${RESET}"
    export PS1=$PS_FULL
fi
    # (deprecated: irrelevant since using "vcprompt")
    # GIT_PS1_SHOWDIRTYSTATE=           # unstaged (*) and staged (+) changes
    # GIT_PS1_SHOWSTASHSTATE=1          # something stashed ($)
    # GIT_PS1_SHOWUNTRACKEDFILES=       # untracked files (%)
    # export PS1='\h:\w \u`__git_ps1`\$ '

# BASH ETERNAL HISTORY
shopt -s histappend
export HISTCONTROL=ignoredups:erasedups:ignorespace
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="%F %T "

# JAVA ENVIRONMENT
export JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"
source_from_path $LOCAL_SCRIPTS/mvncolor.sh

# BASH COMPLETION
source_from_brew etc/bash_completion

# 3rd PARTY SOURCES
source_from_brew etc/autojump.sh
source_from_path ~/.asdf/asdf.sh
source_from_path ~/.asdf/completions/asdf.bash

eval $(thefuck --alias)
export THEFUCK_REQUIRE_CONFIRMATION='false'

# Work related
source_from_path ~/.dotfiles_work/bash_profile.sh
